Add controllers
vasilenkodm/java-shareit pull request #1
Opened 2023-04-11 15:35 UTC by vasilenkodm

2023-04-12 07:34 UTC, LexLippi requested changes
Привет!

Неплозая работа!

Но есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/exceptions/ControllerExceptionHandler.java
> +        bodyMap.put(ERROR, ex.getMessage());
Не уверен в этом с точки зрения безопасности.
Кажется, что отдавать пользователю весь стектрейс исключения не лучшая идея, это может стать причиной для атак.

Логи нужны в основном для разработчиков, пользователю и с точки зрения удобства, и с точки зрения безопасности, необходио только отдавать о каких-то проблемах в запросе или на сервере. Без подробностей

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/exceptions/ControllerExceptionHandler.java
> +        bodyMap.put(ERROR, ex.getMessage());
Это касается всех хэндлеров, в том числе тех, которые ниже

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/exceptions/KeyNotFoundException.java
> +        log.warn(message);
Ты везде выводишь это исключение. Так логи могут засориться однотипными ошибками. Не стоит так делать, логи занимают большую часть дискового пространства на сервере. Так что дублировать лишний раз их не стоит

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/exceptions/KeyNotFoundException.java
> +        log.warn(message);
Это всех исключений касается

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +@SuppressWarnings("unused")
Кажется, при правильной реализации. IDE не должна тебе подсвечивать этот класс и его методы, как `unused` и эта аннотация будет лишней

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/fields/ItemAvailable.java
> +    }
Если `unused`, может удалить?
Чем больше таких аннотаций, тем сложнее поддерживать такой код.

На эту тему есть принцип, который называется `KISS`:
https://en.wikipedia.org/wiki/KISS_principle

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/fields/ItemDescription.java
> +    }
Зачем, если у родительского метода уже есть такой конструктор. Мы же ничего нового не добавляем

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/fields/ItemId.java
> +    }
Аналогично

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/fields/ItemName.java
> +    }
Писал, про это уже

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/fields/ItemName.java
> +    }
Зачем переопределять родительский метод, если мы ничего в него не добавляем?

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +public interface ItemRepository {
Интерфейс не должен подсвечиваться, как `unused`

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    }
Зачем этот метод в интерфейсе?

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMem.java
> +@SuppressWarnings("unused")
Не должно быть `unused`

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMem.java
> +    }
Зачем переопределять метод из интерфейса ничего в нем не меняя?

2023-04-12 07:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMem.java
> +    @SuppressWarnings("unused")
Про `unused` писал уже неоднократно. Если где-то пропустил, то обрати внимание сам, и убери лишние использования этой аннотации

2023-04-12 07:34 UTC, LexLippi commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
такие данные не стоит оставлять в конфиге, все это надо удалять

2023-04-12 07:34 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/ShareItTests.java
>  	}
Интересный тест. Зачем он?)

2023-04-12 19:03 UTC, vasilenkodm commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +@SuppressWarnings("unused")
С классов уберу, но методы без аннотации показываются как проблемные.
![изображение](https://user-images.githubusercontent.com/59884542/231559021-82681520-3396-4330-9209-d5916f6242be.png)

2023-04-12 19:06 UTC, vasilenkodm commented on src/main/java/ru/practicum/shareit/item/fields/ItemDescription.java
> +    }
Компилятор не соглашается.
![изображение](https://user-images.githubusercontent.com/59884542/231559673-2ecaddd5-b5cc-4f7b-aba4-d5847ccdfc87.png)

2023-04-12 19:11 UTC, vasilenkodm commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMem.java
> +    @SuppressWarnings("unused")
Оставляю на методах, иначе "problems":
![изображение](https://user-images.githubusercontent.com/59884542/231560622-52296c3a-72e0-4c95-ad9f-2b8cc679cdf3.png)

2023-04-12 19:18 UTC, vasilenkodm commented on src/main/java/ru/practicum/shareit/item/fields/ItemName.java
> +    }
Переопределяем, чтобы по аннотации @Valid из ItemDTO/UserDTO проверки провалились внутрь полей Item*/User* и выполнили валидацию.

2023-04-12 19:33 UTC, vasilenkodm commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    }
Вытащил метод в интерфейс, для единообразного размещения мест формирования текстов ошибки. UserRepository.userNotFound вызывается в т.ч. из ItemService, полагаю на следующем спринте  ItemRepository.itemNotFound тоже потребуется во вне ItemRepository*.

2023-04-12 19:54 UTC, vasilenkodm commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
Прощай цветной вывод в консоль.

2023-04-12 19:55 UTC, vasilenkodm commented on src/test/java/ru/practicum/shareit/ShareItTests.java
>  	}
Ну надо же хоть что-то проверить в тесте!

2023-04-13 06:40 UTC, LexLippi approved these changes
Привет!

Ок, работу приму. Аннотации надо починить, методы и классы со спринговыми аннотациями не должны подсвечиваться, как `unused`.

Попробуй по этим ссылкам посмотреть:
- https://stackoverflow.com/questions/5283972/telling-intellij-idea-which-methods-not-to-identify-as-unused
- https://stackoverflow.com/questions/60075453/intellij-spring-annotations-are-not-recognized-do-not-trigger-auto-import-manu

Это первые попавшиеся, но может помогут.

Желаю удачи!

2023-04-13 06:47 UTC, merged